#spring.application.name=ApiGetwayServer
#server.port=8084
#eureka.client.service-url.default-zone=http://localhost:8761/eureka
#spring.cloud.gateway.discovery.locator.enabled=true


server:
  port: 8089
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
 
spring:
  application:
    name: SpringCloudGetway
  cloud:
    gateway:
      routes:
      - id: Microservice1
        uri: lb://Microservice1
        predicates:
          - Path=/first_service/**